[tool.poetry]
name = "better-automation"
version = "0.1.7"
description = "Site automation tools"
authors = ["Alen <alen.kimov@gmail.com>"]
readme = "README.md"
packages = [{include = "better_automation"}]

[tool.poetry.dependencies]
python = "^3.11"
pyuseragents = "^1.0.5"
tqdm = "^4.66.1"
aioimaplib = "^1.0.1"
python-socks = {extras = ["asyncio"], version = "^2.3.0"}
aiohttp = "^3.8.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
