[tool.poetry]
name = "better-automation"
version = "2.0.2"
description = "Unofficial Twitter and Discord API"
authors = ["Alen <alen.kimov@gmail.com>"]
readme = "README.md"
packages = [{include = "better_automation"}]

[tool.poetry.dependencies]
python = ">=3.11"
curl-cffi = ">=0.5.10"
yarl = ">=1.9"
tqdm = ">=4.66"
pydantic = ">=2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
