[tool.poetry]
name = "better-automation"
version = "0.5.2"
description = "Site automation tools"
authors = ["Alen <alen.kimov@gmail.com>"]
readme = "README.md"
packages = [{include = "better_automation"}]

[tool.poetry.dependencies]
python = "^3.11"
tqdm = "^4.66.1"
pyuseragents = "^1.0.5"
aioimaplib = "^1.0.1"
aiohttp-socks = "^0.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
