[tool.poetry]
name = "better-automation"
version = "2.0.0"
description = "Unofficial Twitter and Discord API"
authors = ["Alen <alen.kimov@gmail.com>"]
readme = "README.md"
packages = [{include = "better_automation"}]

[tool.poetry.dependencies]
python = "^3.11"
curl-cffi = "^0.5.10"
yarl = "^1.9.3"
tqdm = "^4.66.1"
pydantic = "^2.5.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
